// Инженерные шаблоны и демонстрационные сборки BeesCAD.

import type { CadDocument } from './types';

export interface CadTemplateItem {
  id: string;
  name: string;
  subtitle: string;
  build: () => CadDocument;
}

export function createDemoGearboxDoc(): CadDocument {
  return {
    version: 1,
    name: 'Приводной узел редуктора ЧПУ',
    unit: 'mm',
    defaultMaterialId: 'al-6061',
    gridSizeMm: 10,
    snapMm: 1,
    rollbackIndex: -1,
    section: {
      enabled: false,
      axis: 'X',
      offset: 0,
      flip: false,
    },
    parameters: [
      { id: 'p-base-w', name: 'Base_Width', value: 84, unit: 'mm', comment: 'Ширина опорной плиты' },
      { id: 'p-base-d', name: 'Base_Depth', value: 64, unit: 'mm', comment: 'Глубина опорной плиты' },
      { id: 'p-base-h', name: 'Base_Thick', value: 10, unit: 'mm', comment: 'Толщина плиты' },
      { id: 'p-gear-m', name: 'Gear_Module', value: 2, unit: 'mm', comment: 'Модуль зацепления m' },
      { id: 'p-gear-z', name: 'Gear_Teeth', value: 18, unit: 'count', comment: 'Число зубьев шестерни z' },
    ],
    features: [
      {
        id: 'sk-base',
        kind: 'sketch',
        name: 'Эскиз 1: Опорная плита',
        plane: 'XY',
        planeOffset: 0,
        visible: true,
        shapes: [
          {
            id: 'sh-base-rect',
            kind: 'rect',
            cx: 0,
            cy: 0,
            width: 84,
            height: 64,
            radius: 8,
            innerRadius: 0,
            sides: 4,
            rotationDeg: 0,
          },
        ],
        constraints: [
          { id: 'c-1', kind: 'horizontal', shapeIds: ['sh-base-rect'], label: 'Горизонтальность базы' },
          { id: 'c-2', kind: 'symmetric', shapeIds: ['sh-base-rect'], label: 'Симметрия относительно (0,0)' },
        ],
      },
      {
        id: 'ext-base',
        kind: 'extrude',
        name: 'Выдавливание 1: Плита основания',
        sketchId: 'sk-base',
        distance: 10,
        symmetric: false,
        draftDeg: 0,
        operation: 'new',
        materialId: 'al-6061',
      },
      {
        id: 'ch-base',
        kind: 'chamfer',
        name: 'Фаска 1: Кромки плиты 1.5×45°',
        distance: 1.5,
        angleDeg: 45,
        edgeGroup: 'top',
        targetBodyId: 'body-ext-base',
      },
      {
        id: 'hole-center',
        kind: 'hole',
        name: 'Отверстие 1: Посадка под подшипник Ø22',
        holeType: 'counterbore',
        diameter: 14,
        depth: 10,
        cbDiameter: 22,
        cbDepth: 7,
        csAngleDeg: 90,
        axis: 'Y',
        tx: -14,
        ty: 10,
        tz: 0,
        targetBodyId: 'body-ext-base',
      },
      {
        id: 'std-bearing',
        kind: 'standard_part',
        name: 'Подшипник 608ZZ (8×22×7)',
        partType: 'bearing',
        nominalDiameter: 8,
        length: 7,
        moduleOrPitch: 3.5,
        teethOrCount: 8,
        outerWidth: 22,
        outerDepth: 22,
        wallThickness: 2.2,
        materialId: 'steel-304',
        tx: -14,
        ty: 4,
        tz: 0,
      },
      {
        id: 'std-gear-drive',
        kind: 'standard_part',
        name: 'Шестерня ведущая (m=2, z=18)',
        partType: 'spur_gear',
        nominalDiameter: 8,
        length: 12,
        moduleOrPitch: 2,
        teethOrCount: 18,
        outerWidth: 40,
        outerDepth: 40,
        wallThickness: 4,
        materialId: 'brass-ls59',
        tx: -14,
        ty: 11,
        tz: 0,
      },
      {
        id: 'std-gear-driven',
        kind: 'standard_part',
        name: 'Шестерня ведомая (m=2, z=12)',
        partType: 'spur_gear',
        nominalDiameter: 6,
        length: 12,
        moduleOrPitch: 2,
        teethOrCount: 12,
        outerWidth: 28,
        outerDepth: 28,
        wallThickness: 3.5,
        materialId: 'steel-45',
        tx: 16,
        ty: 11,
        tz: 0,
        ry: 15,
      },
      {
        id: 'std-bolt-1',
        kind: 'standard_part',
        name: 'Винт DIN 912 М5×16 (крепёж)',
        partType: 'socket_bolt',
        nominalDiameter: 5,
        length: 12,
        moduleOrPitch: 0.8,
        teethOrCount: 6,
        outerWidth: 8.5,
        outerDepth: 8.5,
        wallThickness: 5,
        materialId: 'titanium-gr5',
        tx: 32,
        ty: 2,
        tz: 22,
      },
    ],
  };
}

export function createSpindleBracketDoc(): CadDocument {
  return {
    version: 1,
    name: 'Кронштейн шагового привода NEMA 17',
    unit: 'mm',
    defaultMaterialId: 'al-6061',
    gridSizeMm: 10,
    snapMm: 1,
    rollbackIndex: -1,
    section: { enabled: false, axis: 'X', offset: 0, flip: false },
    parameters: [
      { id: 'p-1', name: 'NEMA_Pitch', value: 31, unit: 'mm', comment: 'Межцентровое расстояние NEMA 17' },
      { id: 'p-2', name: 'Pilot_Bore', value: 22, unit: 'mm', comment: 'Центрирующий поясок Ø22 мм' },
    ],
    features: [
      {
        id: 'std-bracket',
        kind: 'standard_part',
        name: 'Кронштейн угловой силовой 50×50×44',
        partType: 'angle_bracket',
        nominalDiameter: 6,
        length: 52,
        moduleOrPitch: 1,
        teethOrCount: 2,
        outerWidth: 44,
        outerDepth: 52,
        wallThickness: 6,
        materialId: 'al-6061',
      },
      {
        id: 'hole-nema-bore',
        kind: 'hole',
        name: 'Отверстие центрирующее Ø22',
        holeType: 'simple',
        diameter: 22,
        depth: 6,
        cbDiameter: 26,
        cbDepth: 2,
        csAngleDeg: 90,
        axis: 'Y',
        tx: 6,
        ty: 6,
        tz: 0,
        targetBodyId: 'body-std-bracket',
      },
      {
        id: 'fillet-bracket',
        kind: 'fillet',
        name: 'Скругление наружных кромок R2',
        radius: 2,
        edgeGroup: 'top',
        targetBodyId: 'body-std-bracket',
      },
    ],
  };
}

export function createEnclosureTemplateDoc(): CadDocument {
  return {
    version: 1,
    name: 'Корпус РЭА с радиатором охлаждения',
    unit: 'mm',
    defaultMaterialId: 'abs',
    gridSizeMm: 10,
    snapMm: 1,
    rollbackIndex: -1,
    section: { enabled: false, axis: 'Z', offset: 0, flip: false },
    parameters: [
      { id: 'p-enc-w', name: 'Box_Length', value: 86, unit: 'mm', comment: 'Длина корпуса' },
      { id: 'p-enc-d', name: 'Box_Width', value: 58, unit: 'mm', comment: 'Ширина корпуса' },
      { id: 'p-enc-h', name: 'Box_Height', value: 26, unit: 'mm', comment: 'Высота борта' },
    ],
    features: [
      {
        id: 'std-enc',
        kind: 'standard_part',
        name: 'Корпус РЭА со стойками М3 (86×58×26)',
        partType: 'pcb_enclosure',
        nominalDiameter: 3,
        length: 26,
        moduleOrPitch: 6,
        teethOrCount: 4,
        outerWidth: 86,
        outerDepth: 58,
        wallThickness: 2.5,
        materialId: 'abs',
      },
      {
        id: 'std-hs',
        kind: 'standard_part',
        name: 'Радиатор силового модуля 44×36×14',
        partType: 'heatsink',
        nominalDiameter: 3,
        length: 14,
        moduleOrPitch: 2.0,
        teethOrCount: 8,
        outerWidth: 44,
        outerDepth: 36,
        wallThickness: 3,
        materialId: 'al-6061',
        tx: 0,
        ty: 8.5,
        tz: 0,
      },
    ],
  };
}

export function createFlangeAssemblyDoc(): CadDocument {
  return {
    version: 1,
    name: 'Фланцевое соединение высокого давления DN32',
    unit: 'mm',
    defaultMaterialId: 'steel-304',
    gridSizeMm: 10,
    snapMm: 1,
    rollbackIndex: -1,
    section: { enabled: false, axis: 'X', offset: 0, flip: false },
    parameters: [
      { id: 'p-dn', name: 'Bore_DN', value: 32, unit: 'mm', comment: 'Условный проход DN32' },
      { id: 'p-od', name: 'Flange_OD', value: 82, unit: 'mm', comment: 'Наружный диаметр диска' },
    ],
    features: [
      {
        id: 'std-flange-main',
        kind: 'standard_part',
        name: 'Фланец воротниковый DN32 (ГОСТ 33259)',
        partType: 'flange',
        nominalDiameter: 32,
        length: 24,
        moduleOrPitch: 8.5,
        teethOrCount: 6,
        outerWidth: 82,
        outerDepth: 82,
        wallThickness: 9,
        materialId: 'steel-304',
      },
      {
        id: 'prim-gasket',
        kind: 'primitive',
        name: 'Кольцо уплотнительное медное',
        shape: 'torus',
        width: 44,
        depth: 44,
        height: 4,
        radius: 22,
        radius2: 2.2,
        wall: 2.2,
        operation: 'new',
        materialId: 'copper-m1',
        tx: 0,
        ty: 24,
        tz: 0,
      },
    ],
  };
}

export function createEmptyDoc(): CadDocument {
  return {
    version: 1,
    name: 'Новая деталь',
    unit: 'mm',
    defaultMaterialId: 'al-6061',
    gridSizeMm: 10,
    snapMm: 1,
    rollbackIndex: -1,
    section: { enabled: false, axis: 'X', offset: 0, flip: false },
    parameters: [
      { id: 'p-w', name: 'Width', value: 40, unit: 'mm', comment: 'Ширина базового контура' },
      { id: 'p-h', name: 'Height', value: 20, unit: 'mm', comment: 'Высота выдавливания' },
    ],
    features: [
      {
        id: 'sk-1',
        kind: 'sketch',
        name: 'Эскиз 1 (XY)',
        plane: 'XY',
        planeOffset: 0,
        visible: true,
        shapes: [
          {
            id: 'sh-1',
            kind: 'rect',
            cx: 0,
            cy: 0,
            width: 40,
            height: 40,
            radius: 4,
            innerRadius: 0,
            sides: 4,
            rotationDeg: 0,
          },
        ],
        constraints: [],
      },
      {
        id: 'ext-1',
        kind: 'extrude',
        name: 'Выдавливание 1',
        sketchId: 'sk-1',
        distance: 20,
        symmetric: false,
        draftDeg: 0,
        operation: 'new',
        materialId: 'al-6061',
      },
    ],
  };
}

export const CAD_TEMPLATES: CadTemplateItem[] = [
  {
    id: 'demo-gearbox',
    name: 'Приводной узел редуктора ЧПУ',
    subtitle: 'Плита основания + подшипник 608 + пара шестерён + крепёж',
    build: createDemoGearboxDoc,
  },
  {
    id: 'spindle-bracket',
    name: 'Кронштейн шагового двигателя NEMA 17',
    subtitle: 'Усиленный уголок Д16Т с центрирующей расточкой Ø22',
    build: createSpindleBracketDoc,
  },
  {
    id: 'pcb-enclosure',
    name: 'Приборный корпус РЭА + радиатор',
    subtitle: 'Корпус со стойками М3 под печатную плату и охлаждением',
    build: createEnclosureTemplateDoc,
  },
  {
    id: 'flange-dn32',
    name: 'Фланцевое соединение DN32 (ГОСТ 33259)',
    subtitle: 'Воротниковый фланец из нержавеющей стали с медным кольцом',
    build: createFlangeAssemblyDoc,
  },
  {
    id: 'empty-part',
    name: 'Чистая деталь (Базовый эскиз + Выдавливание)',
    subtitle: 'Начать моделирование новой детали с нуля',
    build: createEmptyDoc,
  },
];
